-- require "config/statusline"
-- require("tmux").setup {
--   copy_sync = {
--     enable = false,
--   },
--   navigation = {
--     cycle_navigation = true,
--     enable_default_keybindings = true,
--     persist_zoom = false,
--   },
-- }
