require('plugins')
require('config.variables')
require('options')
require('mappings')
vim.cmd('source $HOME/.config/nvim/vim/colors.vim')
require('config.signs')
require('config.lsp')
require('config.telescope')
require('config.treesitter')
require('config.completion')
require('config.others')
vim.cmd('source $HOME/.config/nvim/vim/sandwich.vim')
vim.cmd('source $HOME/.config/nvim/vim/commands.vim')
vim.cmd('source $HOME/.config/nvim/vim/functions.vim')
vim.cmd('source $HOME/.config/nvim/vim/abbrev.vim')
require('config.dap')
