cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev q1 q!
cnoreabbrev Q1 q!
cnoreabbrev WQ wq
cnoreabbrev Wq wq
cnoreabbrev Qa qa
cnoreabbrev Qa1 qa!
cnoreabbrev QA qa
cnoreabbrev QA! qa
cnoreabbrev W! w!
cnoreabbrev Q! q!
cnoreabbrev qw wq
cnoreabbrev Qw wq
cnoreabbrev QW wq
cnoreabbrev qW wq
cnoreabbrev WQa wqa
cnoreabbrev wQa wqa
cnoreabbrev WQA wqa
cnoreabbrev puhs push
